//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForeign
    {
        public int id { get; set; }
        public string Tcno { get; set; }
        public string Tel { get; set; }
        public Nullable<int> PrimaryId { get; set; }
    }
}
